language: python
python:
- 2.7
- 3.4
install:
- pip install sphinx coveralls
script:
- coverage run "--include=LowVoltage/*" setup.py test
- if [ "v$TRAVIS_PYTHON_VERSION" == "v2.7" ]; then python setup.py build_sphinx --builder=doctest; fi
after_success:
- coveralls
